### ISSUE TITLE
Not able to verify connection between robot and workstation, but ping test works 

### ISSUE THREAD

**Issue by rufaidahsalim** [frankaemika/franka_ros#114]
I am trying to connect the Franka Robot to my laptop as workstation. I'm using LAN connection between laptop and control.
 I performed all the steps given at https://frankaemika.github.io/docs/getting_started.html
but not being able run this command -  ./examples/echo_robot_state <fci-ip> (All the files, dependencies have been downloaded)
I get this ERROR: bash: ./examples/echo_robot_state: No such file or directory
 All the files, dependencies for libfranka and frank-ros have been downloaded. 
ROS version -Kinetic
Ubuntu 16.04 LTS

**Comment by gollth** [comment]
Hi @rufaidahsalim,

sorry for the late reply. This is because you have to _compile_ libfranka first. Therefore please follow [these instructions](https://frankaemika.github.io/docs/installation_linux.html#building-libfranka). Then inside you build folder you should have the examples:

```bash
$ cd path/to/libfranka
$ ls build/examples
cartesian_impedance_control  generate_cartesian_pose_motion      joint_impedance_control
CMakeFiles                   generate_cartesian_velocity_motion  joint_point_to_point_motion
cmake_install.cmake          generate_consecutive_motions        libexamples_common.a
communication_test           generate_elbow_motion               Makefile
CTestTestfile.cmake          generate_joint_position_motion      motion_with_control
echo_robot_state             generate_joint_velocity_motion      print_joint_poses
force_control                grasp_object                        vacuum_object

$ build/examples/echo_robot_state YOUR_ROBOT_IP
```

If you installed libfranka via apt should also be able to run the examples directly via ROS:

```bash
rosrun libfranka echo_robot_state YOUR_ROBOT_IP
```

Feel free to reopen this issue when you still have problems.
