### ISSUE TITLE
Cloning and controlling two frankas

### ISSUE THREAD

**Issue by albertojl96** [frankaemika/franka_ros#169]
Hi all,

I am trying to duplicate both franka models in Gazebo for simulation by following the documentation example on franka's website, but once I launch the file given by them, first robot can be controlled whereas the second remains at its home position.
Anyone who had the same problem?

<launch>

  <include file="$(find gazebo_ros)/launch/empty_world.launch" >
    
    <arg name="paused" value="true"/>
    <arg name="use_sim_time" value="true"/>
  </include>

 <include file="$(find franka_gazebo)/launch/panda.launch">
   <arg name="arm_id"     value="panda_1" />
   <arg name="y"          value="-0.5" />
   <arg name="controller" value="cartesian_impedance_example_controller" />
   <arg name="rviz"       value="false" />
   <arg name="gazebo"     value="false" />
   <arg name="paused"     value="true" />
 </include>

 <include file="$(find franka_gazebo)/launch/panda.launch">
   <arg name="arm_id"     value="panda_2" />
   <arg name="y"          value="0.5" />
   <arg name="controller" value="force_example_controller" />
   <arg name="rviz"       value="false" />
   <arg name="gazebo"     value="false" />
   <arg name="paused"     value="false" />
 </include>

</launch>

**Comment by gollth** [comment]
Hi @albertojl96,

I assume you refer to the launch file example in https://frankaemika.github.io/docs/franka_ros.html#customization?

What you describe is expected behavior, since the example given there starts one panda with the `cartesian_impedance_example_controller` and the other with the `force_example_controller`. Simply change both to be Cartesian impedance depending on your application. Then you should be able to control both Pandas with Interactive Markers:

![dual-panda-gazebo](https://user-images.githubusercontent.com/31999281/135113200-bc1ffd56-120e-4722-a1c9-df06cbd0600c.gif)

Feel free to reopen if issue persists
