### ISSUE TITLE
"stopping" function not working properly

### ISSUE THREAD

**Issue by pietrobalatti** [frankaemika/franka_ros#24]
I tried to implement the _stopping_ function in the same way you do for _init_, _starting_ and _update_ but it doesn't seem to be working as expected. What happens is that the function is called immediately after _starting_ and not when the the program is exited (CTRL-C is the appropriate method, isn't it?).

Moreover the starting function is called twice, to be clear this is the order:

init
starting
stopping
starting
update loop

How can I fix this? Thanks

**Comment by fwalch** [comment]
This happens because the controllers are currently [reset in the control node](https://github.com/frankaemika/franka_ros/blob/3f695940b95af8b72fcefc2f65ec6f31da5a1b80/franka_control/src/franka_control_node.cpp#L139-L141) before starting execution. The full lifecycle should therefore be something like:

init
starting
stopping
starting
update loop
stopping

Is this a problem for your controller?

Note that the controller will also be reset after running automatic error recovery (necessary e.g. after a collision), so your controller should be able to handle this.

**Comment by pietrobalatti** [comment]
I found out that I was switching the controller in the wrong way (CTRL-C). The right procedure to do that is:

rosservice call /controller_manager/switch_controller

Thank you
