### ISSUE TITLE
Release to ROS Melodic LTS

### ISSUE THREAD

**Issue by davetcoleman** [frankaemika/franka_ros#34]
MoveIt! is making a big push for Melodic right now and our tutorials do not work as well without franka_ros released:
https://github.com/ros-planning/moveit/pull/1098

**Comment by ch1bo** [comment]
We plan to update our ROS packages to melodic as well, development is currently scheduled for november.

**Comment by davetcoleman** [comment]
Thanks for the quick reply!

Could we get the franka_description released any earlier? Because its the example robot for all of MoveIt!, our Melodic tutorials are currently broken and our CI doesn't pass.

**Comment by gavanderhoorn** [comment]
Related ROS Answers post: [Moveit! tutorials on ROS Melodic](http://answers.ros.org/question/303278).

**Comment by fwalch** [comment]
> Could we get the franka_description released any earlier?

Sure! See release PR here: https://github.com/ros/rosdistro/pull/19307

**Comment by kargarisaac** [comment]
Hi,
Isn't there any melodic version for franka_ros and libfrabka yet?

**Comment by ZakariaChekakta** [comment]
Is there in new about Melodic verison?

**Comment by fwalch** [comment]
Building `libfranka` and `franka_ros` from source with Ubuntu 18.04/ROS Melodic has been possible since libfranka 0.6.0, where we fixed some issues related to newer versions of GCC and Doxygen.
As for packaging for ROS, this has been merged recently (https://github.com/ros/rosdistro/pull/21739, https://github.com/ros/rosdistro/pull/21715) and should show up in the repositories soon (see [here](http://repositories.ros.org/status_page/melodic_default.html?q=franka) for status). Sorry for taking so long.
