### ISSUE TITLE
Moving gripper using Moveit and Rviz

### ISSUE THREAD

**Issue by akashcastelino** [frankaemika/franka_ros#48]
Hi,

In demo.launch when using the 'panda_arm' move group, I can plan a motion using the interactive arrow markers.

But when I use the 'hand' move group, I am not able to interact with the hand to open/close the hand fingers.

Could someone tell me if this is possible in demo.launch, i.e. to manually move the gripper fingers of the 'hand' move group ?

P.s. For the 'hand' move group, in Planning>Select Goal Pose when I choose 'Random' and Execute, the grippers do move to a random position. But, Im not able to find a way to manually move the finger grippers(with arrow markers like with the 'panda_arm' move group)

This image shows robot arm move group with arrow markers moving as expected:
![arm_motionplanning_hasarrows](https://user-images.githubusercontent.com/32956844/51700300-10cd5080-200f-11e9-9d65-1fcced23c48d.png)

This image shows the hand move group which I cannot interact with to move:
![endeffector_noarrows_for_motionplanning](https://user-images.githubusercontent.com/32956844/51700307-13c84100-200f-11e9-87be-94a6bb64885a.png)

**Comment by fwalch** [comment]
The MoveIt config is now maintained at https://github.com/ros-planning/panda_moveit_config, so it's probably better to ask your question there. I am not sure if MoveIt even supports this kind of interaction with grippers from RViz. Otherwise, the MoveIt config needs to be fixed somehow.

FWIW, with a real robot, you can use several actionlib actions to control the gripper with a [franka_gripper_node](http://wiki.ros.org/franka_gripper).

**Comment by gavanderhoorn** [comment]
To keep things connected: I believe this is a cross-post of [Open/Close end effector with Moveit Rviz](http://answers.ros.org/question/313637) on ROS Answers.
