### ISSUE TITLE
Robot control with 3 components Arm <--> Nuc <--> Base station(GPU)

### ISSUE THREAD

**Issue by melfm** [frankaemika/franka_ros#77]
System versions:
ROS distribution -> 'melodic'
libfranka version -> '0.7.1'

What is the best way to communicate with the arm using a **third** computer? The arm is hooked up to a NUC device and I'd like to run my algorithm on a computer with a GPU which can talk to the NUC (but not to the arm directly). How can I use the `controller_manager`, in order to setup the following:

- NUC creates a Robot instance and handles communication with the arm
- A position controller running on a third pc which receives robot state and position from nuc and send updated positions which goes through nuc, and then passed to the robot.

I assume there's a way to do this but I didn't find any relevant controller examples (all assume controller setup and loop is happening on a single machine).

**Comment by dhartaifb** [comment]
Probably the best way is to use the NUC as the ROS Master and connect to this one from your third machine. 

[Link to Tutorial - how to use multiple machines](https://husarion.com/tutorials/ros-tutorials/5-running-ros-on-multiple-machines/)

As a sidenode: The issue section for this repo isn't the best way to get answers because it isn't intended for this purpose. Better use the community forum the next time.
